version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: my_mysql
    restart: always
    command: --log-error-verbosity=2
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: bot
      MYSQL_USER: usr
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: bot
    depends_on:
      - mysql

volumes:
  mysql_data: